### ISSUE TITLE
Database Provider

### ISSUE THREAD

**Issue by morgenmuesli** [SE-Projekt-LED-Detection/LED-Detection#14]
## Feature 
As a User I want to have a possibility to store the Specification online. For that there is a need of a database for up and downloading the pairs of reference image and annotations

## Reason

This Feature is important that specifications can be stored global and doesn't have to stored local

## Criteria

- [ ] connect to Database
- [ ] store Annotation in Database
- [ ] upload img to server 
- [ ] add img url into database

**Comment by olfarmer** [comment]
Uploading to a database is considered not necessary anymore as it would be to inflexible.
