### ISSUE TITLE
Feature Detection

### ISSUE THREAD

**Issue by morgenmuesli** [SE-Projekt-LED-Detection/LED-Detection#25]
## Feature

As developer the feature of the board should be detect with an reference picture of the board.
Those features can either detect by HOG + SVM [hog_svm], SIFT or other more classical OpenCV algorithms.

## Reason

Without those detections it is impossible to detect the board pose orientations

## Criteria

- [x] SIFT Detection
- [x] Contour detections
- [x] (optional) feature detections on different light conditions

**Comment by olfarmer** [comment]
Already included in the current version. Detection works with different lighting conditions as well.
