### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by morgenmuesli** [SE-Projekt-LED-Detection/LED-Detection#26]
## Feature
The events belong to different event channels (for instance BOOT, ALL). The user shall be able to subscribe to one or more of them. If an event in the subscribed channel occurs the user gets notified.

## Criteria

- [ ] clients can subscribe to channels
- [ ] offers differnt channels
- [ ] coordinator can publish events

**Comment by olfarmer** [comment]
Is not necessary anymore because all LEDs are published and the user may subscribe to the boot LED themself.
